name: "unit/integration tests CI"

on:
  pull_request:
    branches:
      - "development"
  push:
    branches:
      - "main"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install dependencies
        run: |
          cd app
          npm ci
      - name: run tests
        run: |
          cd app
          npm test
